spring.application.name=backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/PickUp

spring.data.mongodb.auto-index-creation=true

pickup.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

pickup.jwt.expiration=86400000

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG